SelaPetShop/SelaPetShop.Client/Controllers/AnimalsController.cs
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Caching.Memory;
using SelaPetShop.Client.Models;
using SelaPetShop.Models.Dtos;
using SelaPetShop.Models.Entities;
using SelaPetShop.Models.Helpers;
using SelaPetShop.Models.Interfaces;
using SelaPetShop.Services.Mappers;

using System;
using System.IO;
using System.Web;

namespace SelaPetShop.Client.Controllers
{
    public class AnimalsController : Controller
    {
        private readonly IRepository<Animal> _contextAnimal;
        private readonly IRepository<Category> _contextCategory;
        private readonly IRepository<Image> _contextImage;
        private readonly IMapper<Animal, AnimalDto> _mapper;
        private readonly IMemoryCache _cache;

        public AnimalsController(IRepository<Animal> context, IMemoryCache cache, IMapper<Animal, AnimalDto> mapper, IRepository<Category> contextCategory, IRepository<Image> contextImage)
        {
            _contextAnimal = context;
            _cache = cache;
            _mapper = mapper;
            _contextCategory = contextCategory;
            _contextImage = contextImage;
        }

        public async Task<IActionResult> Index(int id = 1)
        {
            ViewBag.Title = "Sela's Pet Shop";
            try
            {
                var model = new PageControlViewModel
                {
                    PageNumber = id > 0 ? id : 1,
                    PageSize = 10
                };

                var filter = new Filter
                {
                    PageNumber = model.PageNumber > 0 ? model.PageNumber : 1,
                    PageSize = model.PageSize > 0 ? model.PageSize : 10,
                    Name = model.Name,
                    Category = model.Category
                };

                var key = filter.ToString();
                FilterResponse<Animal> res;
                if (!_cache.TryGetValue(key, out res))
                {
                    res = await _contextAnimal.Get(filter);
                    _cache.Set(key, res, TimeSpan.FromSeconds(180));
                };

                return View(res.Data.Select(p => _mapper.Map(p).Result));
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        public async Task<ActionResult> Details(int id)
        {
            var animal = await _contextAnimal.Get(id);

            if (animal == null)
                return NotFound();


            return View(await _mapper.Map(animal));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddComment(int id)
        {
            var model = await _mapper.Map(await _contextAnimal.Get(id));

            try
            {
                model.Comments.Add(new Comment
                {
                    //CommentId,
                    AnimalId = id,
                    Value = model.Comments.ToString()
                }) ;
                await _contextAnimal.Update(await _mapper.Map(model));

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(ex.Message);
            }
        }
    }
}

SelaPetShop/SelaPetShop.Client/Views/Animals/Details.cshtml
@model SelaPetShop.Models.Dtos.AnimalDto

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @* <link rel="stylesheet" href="~/css/animals.css" />*@
    <title>@ViewData["Title"]</title>
</head>

<body>
    <style>
        .animal-page {
            float: left;
        }

        .pic-container {
            border: 2px solid black;
            float: left;
        }

        .animal-pic{
            object-fit: fill;
            width: 250px;
            height: 250px;
        }

        .animal-details{
            color: palegoldenrod;
            text-shadow: 1px 1px 2px red;
            text-align: left;
        }

        .new-comment-container{
            background: white;
            width: 400px;
            height: 200px;
            opacity: 70%;
        }

        .comment-label {
            font-weight: bold;
        }

        .comment-text{
            width: 100%;
            height: 100px;
            font-size: 14pt;
        }

    </style>

    <div class="animal-page">
        <div class="pic-container">
            <img class="animal-pic" src=" @Html.DisplayFor(model => model.Image.Url)" />
        </div>
        <div class="animal-details">
            <h1>@Html.DisplayFor(model => model.Name)</h1>
            <h5>Animal Category: @Html.DisplayFor(model => model.Category.Name)</h5>
            <h5>Birthdate: @Html.DisplayFor(model => model.Birthdate)</h5>
            <h5>Description:</h5>
            <p>@Html.DisplayFor(model => model.Description)</p>
            @foreach(var comment in Model.Comments)
            {
                <h6>@Html.DisplayFor(modelItem => comment.Value)</h6>
            }
        </div>

        <form class="new-comment-container" asp-controller="Animals" asp-action="AddComment" asp-route-id="@Model.AnimalId">
            @using (Html.BeginForm("Edit", "Animals", FormMethod.Post))
            {
                <div>
                    <label class="comment-label">New Comment:</label>
                </div>
                <div>>
                    @Html.TextBoxFor(model => model.comment, new { @class = "form-control", @placeholder="Text Here.."})
                </div>
                <div>
                    <input type="submit" value="Submit" />
                </div>
            }
        </form>
        <a asp-action="Index">Back To Catalogue</a>
    </div>
</body>
</html>

SelaPetShop/SelaPetShop.Client/Views/Animals/Index.cshtml
@model IEnumerable<SelaPetShop.Models.Dtos.AnimalDto>

@{
    ViewData["Title"] = "Animal Catalogue Page";
}

<head>
    <link rel="stylesheet" href="~/css/animals.css" />
</head>
<div class="table">
    <h1>@ViewBag.Title</h1>
    <table class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Birthdate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Comments)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <img src="@Html.DisplayFor(modelItem=> item.Image.Url)" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Birthdate)
                    </td>
                    @foreach (var comment in item.Comments)
                    {
                        <td>
                            @Html.DisplayFor(modelItem => comment.Value)
                        </td>
                    }
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.AnimalId">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.AnimalId">Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>